language: python
python:
  - "2.7"

before_script:
  - git config --global user.email "travis@travis-ci.org"
  - git config --global user.name "Travis McTravis"
  - cp lib/python/mozilla_buildtools/test/hgrc ~/.hgrc

install:
  - "pip install tox"

script:
  - "tox"

# currently cannot customise per user fork, see:
# https://github.com/travis-ci/travis-ci/issues/1094
notifications:
  irc: "irc.mozilla.org#releng"
  on_success: always
  on_failure: always
